# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e79e0868912fca6d577b8bcfc2c0311c7e47be580acb804299f8662964d64e34b99b17586182aad01cbfc8152a5291d0315aa432f4943ad150dcd8e247d84c02

test:
  secret_key_base: f2038291495f3724812786dc1897812578beb64c1f13b5b68efed8ec3976b19f5a4a72b2c354466087555b0db7a43577d7c0e1e2378e4b5101c610b22878a014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
